### ISSUE TITLE
rest api response convert error (TZ-99)

### ISSUE THREAD

**Issue by HeFeng1947** [espressif/esp-thread-br#10]
https://github.com/espressif/esp-thread-br/blob/4090afb33c6efa37968572cffebe5734ea988d2f/components/esp_ot_br_server/src/esp_br_web_library.c#L175
EUI64 is not a ipv6 address, this conversion will cause an error data.

https://github.com/espressif/esp-thread-br/blob/4090afb33c6efa37968572cffebe5734ea988d2f/components/esp_ot_br_server/src/esp_br_web_package.c#L135
I think it calls an error api and should call `otPlatRadioGetTransmitPower` here.

**Comment by xieqinan** [comment]
Thanks for your suggestion.
