### ISSUE TITLE
Web GUI jQuery not loaded (TZ-1187)

### ISSUE THREAD

**Issue by pierreyves258** [espressif/esp-thread-br#103]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

When reaching the Web GUI via http://ip/index.html the page should display status & allow scan and join

### Actual behavior (suspected bug)

On the index page, nothing see to work properly
The status is "unknown" on all properties
The scan & join does nothing
and the Form network does nothing

However API seem to work fine
(see attached)
![Screenshot 2024-09-28 190604](https://github.com/user-attachments/assets/e2bad143-9c0b-47a9-9f78-272d9f36448e)
![Screenshot 2024-09-28 190329](https://github.com/user-attachments/assets/7082ca34-1d7d-4a92-81d1-d86f373f23aa)

### Error logs or terminal output

```shell
Uncaught ReferenceError: $ is not defined
    <anonymous> http://192.168.1.141/static/restful.js:74
restful.js:74:1
    <anonymous> http://192.168.1.141/static/restful.js:74
```

### Steps to reproduce the behavior

Install esp-thread-br\examples\basic_thread_border_router with following sdkconfig

[sdkconfig.txt](https://github.com/user-attachments/files/17175641/sdkconfig.txt)

### Project release version

master

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Windows 

### Operating system version

Windows 11

### Shell

PowerShell

**Comment by chshu** [comment]
It seems some issue in the frontend. There is a recent change to jQuery: https://github.com/espressif/esp-thread-br/pull/101, could you revert the change, and try again?
