### ISSUE TITLE
thread node OTA (TZ-1249)

### ISSUE THREAD

**Issue by briansuyu** [espressif/esp-thread-br#108]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

Is there an exsample of how to do an OTA to any thread node from a local network computer when a thread network is formed through BR?

**Comment by chshu** [comment]
OTA is kind of an application feature, you may refer to https://github.com/espressif/esp-idf/tree/master/examples/system/ota for the common OTA examples.
