### ISSUE TITLE
log等级设置对于thread协议栈无效 (TZ-155)

### ISSUE THREAD

**Issue by gl-chenxiaosheng** [espressif/esp-thread-br#16]
我从乐鑫仓库的[qcloud](https://github.com/espressif/esp-qcloud)参考了log存储进flash的组件，目前发现该组件能正常将esp_log的接口根据预先设置的log等级进行存储，但是对于thread协议栈的log并不行，请问这是啥原因导致的？

**Comment by chshu** [comment]
试试调用一下这个 API：
```
otLoggingSetLevel(CONFIG_LOG_DEFAULT_LEVEL);
```

**Comment by chshu** [comment]
@gl-chenxiaosheng Please reopen if any follow up questions.
