### ISSUE TITLE
OPENTHREAD_RCP_SPI&OPENTHREAD_RADIO_SPINEL_SPI (TZ-229)

### ISSUE THREAD

**Issue by JiaDeng-Git** [espressif/esp-thread-br#29]
esp-idf/examples/openthread/ot-rcp设置OPENTHREAD_RCP_SPI&OPENTHREAD_RADIO_SPINEL_SPI编译报错：
![image](https://github.com/espressif/esp-thread-br/assets/44760427/fa81495e-ee65-4938-b94c-8d62477e1d2b)

**Comment by chshu** [comment]
在编译 ot_rcp 的需要指定 esp32h2，请按照文档说明操作：
https://docs.espressif.com/projects/esp-thread-br/en/latest/esp32/dev-guide/build_and_run.html#build-the-rcp-image

![image](https://github.com/espressif/esp-thread-br/assets/20312411/c05dca07-19cf-47e3-aa96-6156f66fb997)

**Comment by zwx1995esp** [comment]
如果idf用的是最新的master/或者release/v5.1，rcp和esp-thread-br的example应该没有编译问题，所以开始的那个问题现在还有嘛？

**Comment by chshu** [comment]
第二步编译 ot_rcp 的时候，不要设置 `OPENTHREAD_RCP_SPI` 和 `OPENTHREAD_RADIO_SPINEL_SPI`，默认用 Uart 接口。
