### ISSUE TITLE
ESP Openthread Border Router Board (TZ-53)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-thread-br#3]
Hi,

I am not able to find ESP Openthread border router boarder anywhere. Can you please share a link from where I can buy it?

**Comment by chshu** [comment]
@bilalmalik76 The board will be public availabe Q2 this year, will share the link once it's ready.

**Comment by chshu** [comment]
@bilalmalik76 The ESP Thread Border Router board is public available now: https://www.espressif.com/en/news/Thread_Border_Router_Certification
