### ISSUE TITLE
按照开发文档一步一步来，各种报错！ (TZ-230)

### ISSUE THREAD

**Issue by JiaDeng-Git** [espressif/esp-thread-br#30]
<img width="1108" alt="截屏2023-08-09 01 54 19" src="https://github.com/espressif/esp-thread-br/assets/44760427/b48a5f4c-9c92-4c8c-b1a8-0b4176ecec18">

请问文档是外包给其它公司写的吗？

**Comment by chshu** [comment]
已在另外两个 issue 中答复：
1. 需要更新到较新的 IDF master 或 release/v5.1 branch
2. 编译 ot_rcp 时需要指定 esp32h2

这两个步骤在文档说明中都有：

![image](https://github.com/espressif/esp-thread-br/assets/20312411/4ce4efa1-004a-4b38-b8d7-48aae77e412e)

![image](https://github.com/espressif/esp-thread-br/assets/20312411/9ba92abb-c82e-4131-8a5e-614677fd67f8)

请严格按照文档说明操作。
