### ISSUE TITLE
ESP32H2/ESP32C6 + 树莓派  (TZ-340)

### ISSUE THREAD

**Issue by weitao924** [espressif/esp-thread-br#34]
我想使用树莓派作为OTBR的主机，用ESP32C6/ESP32H2作为Thread RCP，这种方案可否使用该SDK？如果可以，是否支持SDK的全部功能？如果不能，还请各位大佬指教

**Comment by chshu** [comment]
树莓派上跑的是 [ot-br-posix](https://github.com/openthread/ot-br-posix)，可以参考这个链接：https://openthread.io/guides/border-router/raspberry-pi

ESP32C6/ESP32H2 做 Thread RCP 是这个 example：https://github.com/espressif/esp-idf/tree/master/examples/openthread/ot_rcp

**Comment by weitao924** [comment]
> 树莓派上跑的是 [ot-br-posix](https://github.com/openthread/ot-br-posix)，可以参考这个链接：https://openthread.io/guides/border-router/raspberry-pi
> 
> ESP32C6/ESP32H2 做 Thread RCP 是这个 example：https://github.com/espressif/esp-idf/tree/master/examples/openthread/ot_rcp

感谢您的解答
