### ISSUE TITLE
Multicast forwarding (TZ-410)

### ISSUE THREAD

**Issue by briansuyu** [espressif/esp-thread-br#42]
Hi, during testing the basic_thread_boarder_router exsample, i was stucked doing the multicast forwarding codelab, 

after using mcast commond, my esp32boarder router and other 2 esp32h2 FTD all joined ff04::123 multicast group
![image](https://github.com/espressif/esp-thread-br/assets/75798662/0acbcd0e-ce6c-4588-8d75-7f09dabc1a99)
![image](https://github.com/espressif/esp-thread-br/assets/75798662/84806cec-7d40-4ce1-b6d2-5b7fd16151a8)

but when try to ping ff04::123 address from outside windows machine it doesn't response (the windwos route table seems alright, and ping each FTD with there ULA address works)
![image](https://github.com/espressif/esp-thread-br/assets/75798662/30bbc635-061b-4353-ba65-54416e317d9b)

can i ask am i missing any config steps to make this work? Should i add some code to register the netif: en interface to the multicast group as well? (i guess my esp32 boarder router didn't receive the ff04::123 address multicast data because it didn't register it in the outside network?)

**Comment by zwx1995esp** [comment]
Could you please set this command to BR and to see the BBR is enabled or not?

`> bbr`

**Comment by briansuyu** [comment]
> Could you please set this command to BR and to see the BBR is enabled or not?
> 
> `> bbr`

not enabled
![image](https://github.com/espressif/esp-thread-br/assets/75798662/80a2c330-ecbe-4173-9c55-e2a6b659c091)

**Comment by briansuyu** [comment]
after enabling bbr, the multicast forwarding works now. thanks

**Comment by briansuyu** [comment]
hi, about the multicast forwarding,  some other issue comes out when enabling bbr and the multicast not working again. The code was not changed, only some modification in menuconfig about the dataset. Here is the error i see
![image](https://github.com/espressif/esp-thread-br/assets/75798662/1ef0f403-5eac-4f01-82d7-7feac9befc33)
![image](https://github.com/espressif/esp-thread-br/assets/75798662/2c95fa26-0098-4623-892c-f0357565137e)
Can i ask what possible reason could cause this error? I tried clone a completely new clean esp br code and compiled again still the same

**Comment by zwx1995esp** [comment]
Could you please enlarge the configuration to `32` and try again?

(Top) → Component config → mDNS → (16) Maximum actions pending to the server

**Comment by zwx1995esp** [comment]
Also you need to set the `mcast join ff04::123` on a non-BR device. You can flash and run the example `$ESP_IDF/examples/openthread/ot_cli` on an ESP32H2/ESP32C6 and join the network formed by BR, then use this command to listen the multicast address on this device.

**Comment by zwx1995esp** [comment]
I guess you want to try the multicast forwarding feature of the ESP BR, so you need to try like the previous comment.

But if you just want to let the BR join the multicast listenning group on the WiFi netif and ping the BR from host, you can just use the lwip address adding command like this `ip add st ff04::123`(BTW, you can use the lwip address show command `ip print` to log the address allocated on the BR, you can confirm the multicast address does register on the ST netif) then you can ping this multicast address from HOST.

**Comment by briansuyu** [comment]
yes i was trying the multicast forwarding feature. I cleaned everything and tried again with the ot_cli exsample on a h2 mini devboard and increased the mDNS max actions pending size on the esp32 br. Device joined the network formed by the br and can be pined from linux host, bbr enabled, but multicast still fails.
![image](https://github.com/espressif/esp-thread-br/assets/75798662/ad791ba7-2855-4037-9b32-ae5bfc15b9fe)
here is the log on br side.
![image](https://github.com/espressif/esp-thread-br/assets/75798662/62aebf88-03c3-4438-8db1-75cb0a28e073)
![image](https://github.com/espressif/esp-thread-br/assets/75798662/5163bc6f-fa18-408f-b7bf-b3f0e882d5d7)

but i can ping the multicast address from windows powershell
![image](https://github.com/espressif/esp-thread-br/assets/75798662/63af7170-44a9-4734-b47c-21b5b93c60a1)

both machines and br connected to the same switch and router. 
Can i ask is there anything configuration i should set on the linux host?

**Comment by zwx1995esp** [comment]
Yes, for the linux host, I think you can have try with set the `ttl` 64(also named hop limit), some linux host will set 1 as the ttl default value, and maybe you need also specify the net interface in the ping command on the linux host. You can have a try with this command on linux:

```
ping ff04::123 -I <interface name> -t 64
```

Tips: As for the interface name you can obtain it using the command `ifconfig`.

**Comment by briansuyu** [comment]
thanks a lot, with the ttl setting everything finalling works. Thanks

**Comment by zwx1995esp** [comment]
Great! Actually, in our docs, we have already recommend to set the ttl `64` when using a multicast address as a ping dest address. you can refer to [here](https://docs.espressif.com/projects/esp-thread-br/en/latest/codelab/multicast_forwarding.html#reaching-the-multicast-group-from-the-wi-fi-network-via-icmp)
