### ISSUE TITLE
Manual/DHCP DNS Server (TZ-544)

### ISSUE THREAD

**Issue by jeroen79** [espressif/esp-thread-br#54]
Is there a way to set the dns server used but the border router?, it seems to use a google dns server by default.

Using the dns server from DHCP6 would also be acceptable, but using google is just wrong, it won't be able to resolve local hostnames.

**Comment by zwx1995esp** [comment]
So you want to use BR to resolve local service? Or what is your demend? Could you please show me some detials about that?

**Comment by jeroen79** [comment]
Yes i want it to resolve local hostnames eg: server.home.local, and just by able to change the dns server it uses this would be possible, but i can't find any configuration options for it.

My home router is ipv6 capable and it can properly resolve it, i just need to be able to make the border router and all other thread devices use it.

**Comment by zwx1995esp** [comment]
So you mean that the local dns service resolving shown like this [link](https://docs.espressif.com/projects/esp-thread-br/en/latest/codelab/service_discovery.html#publishing-services-from-the-wi-fi-network)? For the thread device in the thread network(not BR device), the dns server should be the BR device. Notice that all the commands shown in the link is related to the OT device, and these commands are implemented in the openthread stack.

As for the BR, it is also a WiFi device, if you want to resolve the service on the wifi interface, you can just use the `mdns` API to query the target service.

**Comment by zwx1995esp** [comment]
And for the thread device, there is a config to set the DNS server, which can be set by `idf.py menuconfig`
```
(Top) → Component config → OpenThread
(8.8.8.8) DNS server address (IPv4)
```
But I don't believe this feature is related to the local service, this server is configured on the BR, and using to access the service on the global network.

**Comment by jeroen79** [comment]
That dns server is only uses for the DNS64 feature i think, i did also set it but it had no effect.

I did manage to force my router to redirect dns to itself, but i think in the future the dns server should be from dhcpv6 or at least configurable in menuconfig, defaulting to a google dns seems wrong to me.

**Comment by zwx1995esp** [comment]
> 
> No my dns server does not use mdns, its a normal lan dns server., is that not sufficient?
> 
Ok, got that.

> ```
> (Top) → Component config → OpenThread
> (8.8.8.8) DNS server address (IPv4)
> ```
> 
> This setting also does not seem to have any effect, if i understand correctly it is only for ipv6->ipv4 conversion.
> 
> There is another way way the system seems to force the google ipv6 dns server, but so far i have not had the time to figure out where is comes from.

No, for the thread device, if it want to resolve some service address, the device will try to send the query packet to the DNS sercer IPv4 embedded IPv6 address, this address constructs by a NAT64 prefix and a IPv4 address. The query packet will first send to BR and BR will deconstruct the address and get the target DNS IPv4 address. And send the packet to the DNS server. If your local server is surely a DNS server, this should be works.

Could you please try to ping the DNS server address on the thread device(not on the BR)? Maybe we need to confirm that the connection between Thread device and DNS server are well.

On the thread device, yuou can just ping command:

```
> ping <your local IPv4 DNS server addr>

For exapmle:
> ping 192.168.1.1
```

**Comment by zwx1995esp** [comment]
Hi, I did a quick test for your scenario. As the previous comments, I set the DNS server using my host address `192.168.1.102` which is a local address, and using the command `curl http://www.baidu.com` on thread device to curl some websites, I see the DNS query packet surely send to the host on wireshark.

Topology:
```
[thread device] <----> [thread BR] <========>[AP,local network] <=====> [my linux host]
```
The IPv4 address of BR is `192.168.1.100`:
 
![image](https://github.com/espressif/esp-thread-br/assets/69466651/1edba0a8-715f-4b0d-97a6-f63a5c931719)

you can see the result, the packet surely sends to the host(192.168.1.102:53),:
![image](https://github.com/espressif/esp-thread-br/assets/69466651/5a4e1ac8-99fc-448f-aee1-1b3dadde9195)

**Comment by chshu** [comment]
@jeroen79 could you help to close the issue if it has been resolved?

**Comment by jeroen79** [comment]
You can close it, i have switched to just using wifi for now, i wasn't satisfied with the current stability of thread on esp32. i might pick it up again later.

**Comment by chshu** [comment]
@jeroen79 The issue you've described appears to be a functional one, and we have a solution for you. Could you provide more details about the stability concerns? We are happy to assist you in resolving any stability issues you may be experiencing.
