### ISSUE TITLE
CAD Model for Border Router (TZ-594)

### ISSUE THREAD

**Issue by TCWilliamson** [espressif/esp-thread-br#55]
Hello,

would it be possible to get a 3D CAD Export for the Border Router? I am designing an enclosure for it.

Thank you!

**Comment by chshu** [comment]
The 3D CAD file is not ready yet, will post here once it's available.

**Comment by TCWilliamson** [comment]
> The 3D CAD file is not ready yet, will post here once it's available.

Any luck yet? It would help as we need to design a top board to go on where the ethernet plugs in, we want to make sure we align the sizes & pins with our CAD & the new PCB. It is important. We will be looking at several hundred of these units soon.

**Comment by chshu** [comment]
@TCWilliamson @martin8310 Please find the CAD files here: https://docs.espressif.com/projects/esp-thread-br/en/latest/hardware_platforms.html#cad
