### ISSUE TITLE
Build files for ESP Thread Border Router v1.2 board (TZ-642)

### ISSUE THREAD

**Issue by djorr5** [espressif/esp-thread-br#60]
Hi,

Are there build files available for the above board? I would like to add additional circuitry to it without having to re-do all the vias for RF tuning.

**Comment by chshu** [comment]
@djorr5 The schematic file is available here: https://docs.espressif.com/projects/esp-thread-br/en/latest/hardware_platforms.html#related-documents.

Could you specify what kinds of build files are you looking for? We will check internally if these can be shared.

**Comment by djorr5** [comment]
The gerbers basically. I could use the PDF schematic to create them but
ideally the already created ones would be a massive time saver. Also you
have a lot of vias on the board, I assume for RF and you board would be
tuned already. I don't want to have to do that part again.

**Comment by chshu** [comment]
@djorr5 The NDA may be required to share the gerber file, could you please get in touch with us via https://www.espressif.com/en/contact-us/sales-questions.

**Comment by djorr5** [comment]
Hi. Every time I try to submit the form at sales-question it fails.

**Comment by chshu** [comment]
@djorr5 Could you send an email to sales@espressif.com?

**Comment by martin8310** [comment]
I would be happy about these files too! Tasmota does that too ;-)
![firmware](https://github.com/espressif/esp-thread-br/assets/62466200/8401879e-3cdd-4777-9fdb-3a2935e31f75)

**Comment by chshu** [comment]
Please contact us via https://www.espressif.com/en/contact-us/sales-questions to request the build/gerber files.
