### ISSUE TITLE
[Question] Can basic-thread-border-router with USB_SERIAL_JTAG work without serial terminal? (TZ-646)

### ISSUE THREAD

**Issue by mmt-10** [espressif/esp-thread-br#61]
Hi,

I would like to use USB  SERIAL `CONFIG_OPENTHREAD_CONSOLE_TYPE_USB_SERIAL_JTAG=y`.
However, I must connect `basic-thread-border-router` to serial terminal(e.g. minicom) for working border router.

Can `basic-thread-border-router` work without connection serial terminal(e.g. minicom)?

**Comment by chshu** [comment]
@mmt-10 It should work as is, you don't need to connect serial terminal.

There was a bug in old IDF version, but it has been fixed long ago, please try with IDF 5.1.2, let us know if you see any issue.

**Comment by mmt-10** [comment]
Thank you for your reply.
I will try with IDF 5.1.2.
