### ISSUE TITLE
Failure to set active dataset (TZ-895)

### ISSUE THREAD

**Issue by motters** [espressif/esp-thread-br#68]
Hi,

We've been copy'ing and past the openthread br code into our project which uses ESP-IDF v5.1 with ESP-Ardunio. 

Everything works as expected however it is not possible to set to set a new dataset active, see below:
<img width="366" alt="image" src="https://github.com/espressif/esp-thread-br/assets/2155687/051524c1-3468-474b-ba52-314bf57f4e8f">

We have tried setting the active dataset through code and though the cli and both fail to set it.
<img width="591" alt="image" src="https://github.com/espressif/esp-thread-br/assets/2155687/76e9f7f5-5d90-496e-9c09-49709cad4997">
 

Our question is:
  - Does ESP-Ardunio (including Preference class) clash with 'esp_openthread_settings.c'?
  - Is there anything else that could stop the dataset becoming active?

Cheers!

Additional info: in esp_openthead_settings.c OT_ERROR_NOT_FOUND is always returned when getting network details
![image](https://github.com/espressif/esp-thread-br/assets/2155687/b4538f3b-8bbc-4353-a5fb-90be8b7817e2)

esp_openthead_settings.c OT_ERROR_NONE is always returned when setting the network details
![image](https://github.com/espressif/esp-thread-br/assets/2155687/88774ad4-94d5-45b1-9b1e-0842c7db19a1)

**Comment by motters** [comment]
Using nvs_tool.py i can conform he OT dataset is being wrote to flash
<img width="1421" alt="image" src="https://github.com/espressif/esp-thread-br/assets/2155687/e4a1bc93-af45-4736-9821-4f902bef6068">

So the question is why can't it read the dataset from flash.

**Comment by motters** [comment]
I think the problem is solved. port_config.storage_partition_name was changed from ot_storage to nvs

This commit was a breaking change our orginal BR months back to the current commit 
https://github.com/espressif/esp-thread-br/commit/f3c952a9ce369f5d6b78e27dd764c8af11fb3d19

**Comment by motters** [comment]
This was indeed the issue encase anyone else has it.

**Comment by zwx1995esp** [comment]
Hi, sorry for missing this issue, we recommend using esp-thread-br v1.0 based IDF v5.1.3. So could you please update your codebase?
