### ISSUE TITLE
[Question] RCP firmware was updated every time when board was powered on (TZ-931)

### ISSUE THREAD

**Issue by briansuyu** [espressif/esp-thread-br#72]
hi, i am debugging a strange behavior on my customized esp32 + esp32H2 board,  the RCP firmware was updated every time when board was powered on. Here is the log:
idf version 5.2.2
esp thread br version: master

1. when board was powered on 1st time,  the internel RCP firmware was not found and then reboot 
![image](https://github.com/espressif/esp-thread-br/assets/75798662/9d61f8bb-72f9-4898-921e-cbc88592e0be)

2.  after reboot, internal RCP firmare was found and running RCP firmware was not found and update process was perfomed
![image](https://github.com/espressif/esp-thread-br/assets/75798662/1ede19a8-111f-475a-98df-3e5b80ab5fcb)
 
![image](https://github.com/espressif/esp-thread-br/assets/75798662/b28fd8b9-5a92-40c5-b1dc-f9880a29630a)

3. after 2nd reboot, then everything seems working 
![image](https://github.com/espressif/esp-thread-br/assets/75798662/3cca9287-3f23-4ef3-aefc-133367577846)

and every time when board was powered off ->on , it go through 1->3 again.

board connection: 
![image](https://github.com/espressif/esp-thread-br/assets/75798662/fc31049a-31de-4372-b8df-992ea8de1c21)

I build several small example tests and test the 2 chips individually. Both chips seems working for those individual module tests.
Could i ask where might the problem be?

**Comment by gytxxsy** [comment]
> hi, i am debugging a strange behavior on my customized esp32 + esp32H2 board, the RCP firmware was updated every time when board was powered on. Here is the log: idf version 5.2.2 esp thread br version: master
> 
> 1. when board was powered on 1st time,  the internel RCP firmware was not found and then reboot
>    ![image](https://private-user-images.githubusercontent.com/75798662/338529587-9d61f8bb-72f9-4898-921e-cbc88592e0be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTk2MTcsIm5iZiI6MTcxODE1OTMxNywicGF0aCI6Ii83NTc5ODY2Mi8zMzg1Mjk1ODctOWQ2MWY4YmItNzJmOS00ODk4LTkyMWUtY2JjODg1OTJlMGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYWIwNDBmNTZiZGNmZmQ5NzhlYTQ5NDU3YjM2MWM0YTQwMDRkM2U4YTgyMGFmMzczMzZlNTA2NTAxOTVhZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TABXKR4sm6UwgnndlVab2Y3-L_HZi0mqAk8ql8eyCEw)
> 2. after reboot, internal RCP firmare was found and running RCP firmware was not found and update process was perfomed
>    ![image](https://private-user-images.githubusercontent.com/75798662/338530425-1ede19a8-111f-475a-98df-3e5b80ab5fcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTk2MTcsIm5iZiI6MTcxODE1OTMxNywicGF0aCI6Ii83NTc5ODY2Mi8zMzg1MzA0MjUtMWVkZTE5YTgtMTExZi00NzVhLTk4ZGYtM2U1YjgwYWI1ZmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZmM3NjYxODNhMDg0MDRiNmQ1MTNmZjZhZTYwZDRhNmUyOThlNWUxNGE1YjIzZDIyZGEyNmI3ODBlMGQ2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uu2C296BXOq3hKCDBB4WID_KlECXUxnN53XztUsfNLc)
> 
> ![image](https://private-user-images.githubusercontent.com/75798662/338530547-b28fd8b9-5a92-40c5-b1dc-f9880a29630a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTk2MTcsIm5iZiI6MTcxODE1OTMxNywicGF0aCI6Ii83NTc5ODY2Mi8zMzg1MzA1NDctYjI4ZmQ4YjktNWE5Mi00MGM1LWIxZGMtZjk4ODBhMjk2MzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZThlMDA3ZWYxMGJmZDgzYWJkMzgyM2I3NThkYTFiZDMzMTliMmZjM2Q0ZWVhOThhZWIxODg1YjUxZGViNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6QB8J68tfVAwX_IlvV4fWaH25wV_0OD_pwCurKa0v7Y)
> 
> 3. after 2nd reboot, then everything seems working
>    ![image](https://private-user-images.githubusercontent.com/75798662/338533661-3cca9287-3f23-4ef3-aefc-133367577846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTk2MTcsIm5iZiI6MTcxODE1OTMxNywicGF0aCI6Ii83NTc5ODY2Mi8zMzg1MzM2NjEtM2NjYTkyODctM2YyMy00ZWYzLWFlZmMtMTMzMzY3NTc3ODQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MTcwZjFiZjRiNTJkYjgzMjZhOTIwNzZlZWFjMjU3NzFlZjRiN2RmYzYzMmZlMjhlZDY1MTQ2Y2UwNTk0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kyMiXyACwoZYia0AtMuOvMxYl9-4hIZTjlizItxtNew)
> 
> and every time when board was powered off ->on , it go through 1->3 again.
> 
> board connection: ![image](https://private-user-images.githubusercontent.com/75798662/338536897-fc31049a-31de-4372-b8df-992ea8de1c21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNTk2MTcsIm5iZiI6MTcxODE1OTMxNywicGF0aCI6Ii83NTc5ODY2Mi8zMzg1MzY4OTctZmMzMTA0OWEtMzFkZS00MzcyLWI4ZGYtOTkyZWE4ZGUxYzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAyMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZTcwN2E2ZWIzMjg5ZGM4OGZlZDljMDA1Nzc3OWIzMmE0YWVjNmZmYjUwNWVkMDBiZDU2N2ZlODdiNDE0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ySIr8Exa6uIFxRpUyCfVsLKMpn3ccwLkx4zEsppbUE)
> 
> I build several small example tests and test the 2 chips individually. Both chips seems working for those individual module tests. Could i ask where might the problem be?

The esp-thread-br example uses ESP32S3 + ESP32H2 by default (refer [hardware platforms](https://docs.espressif.com/projects/esp-thread-br/en/latest/hardware_platforms.html) ). Are you sure you are using ESP32 + ESP32H2? If so, I would like to know if this is an issue that occurs every time. Could you provide more detailed steps to reproduce the problem?
In fact, I modified the project configuration to use ESP32 + ESP32H2, and the other configurations are basically consistent with those in the screenshot you provided (except that Wi-Fi is used instead of Ethernet), but I did not reproduce this issue.
