### ISSUE TITLE
Form thread network in Web GUI doesn't work (TZ-989)

### ISSUE THREAD

**Issue by jeremyherbert** [espressif/esp-thread-br#78]
I am trying to form a network using the web GUI and the default settings in the GUI, but I get an error message:

![SCR-20240704-pxsp](https://github.com/espressif/esp-thread-br/assets/52499/663438f4-b774-4e66-8200-2ddd46956860)

![SCR-20240704-pxun](https://github.com/espressif/esp-thread-br/assets/52499/e405cecb-036d-4f64-a1d3-efc662ca2761)

It appears that the webserver on the ESP32-S3 (thread border router dev kit) is rejecting the POST request:

![SCR-20240704-pyds](https://github.com/espressif/esp-thread-br/assets/52499/462fa9c2-02bf-4e8e-b01a-61aee51b4f06)

I am using Chrome Version 126.0.6478.127 (Official Build) (x86_64)

**Comment by jeremyherbert** [comment]
The fix is to go into `menuconfig` and change `Component config` => `HTTP Server` => `Max HTTP Request Header Length` to a bigger number (I changed from 512 to 2048). Perhaps the default values should be updated in the project? My HTTP headers are nothing unusual, so it seems like the default value is not large enough.

**Comment by zwx1995esp** [comment]
Hi, we have the tests on our ENV using Firefox version:  129.0.2(64bit), all things work fine. I think this issue should be related to the browse. Change the menuconfig seems work.

**Comment by chshu** [comment]
@jeremyherbert It seems not a SDK issue, you can change the default configuration in your application.
