### ISSUE TITLE
esp-thread-br后续会集成ot-br-posix的restful API吗？ (TZ-96)

### ISSUE THREAD

**Issue by HeFeng1947** [espressif/esp-thread-br#8]
目前很多生态对接OTBR都基于ot-br-posix的rest api接口，而esp-thread-br内部有一套简化的版本，但是不太足够，例如缺少网络拓扑等。如果能直接移植ot-br-posix那套C++的代码应该在后续维护和多生态适配都有一定优势。

**Comment by chshu** [comment]
ot-br-posix 是基于 Linux Posix 的，ESP Thread BR 是基于 ESP- IDF (RTOS based)，所以 IP stack / mDNS / web-service 这些基础组件都不一样。

我们会对比一下 rest API，尽可能兼容 ot-br-posix.

**Comment by HeFeng1947** [comment]
> ot-br-posix 是基于 Linux Posix 的，ESP Thread BR 是基于 ESP- IDF (RTOS based)，所以 IP stack / mDNS / web-service 这些基础组件都不一样。
> 
> 我们会对比一下 rest API，尽可能兼容 ot-br-posix.

感谢回复。我们现在正在和HA等第三方生态讨论基于ot-br-posix rest api的对接，如果esp方案可以兼容ot-br-posix的接口，那么我们就可以无缝接入了。

**Comment by chshu** [comment]
@HeFeng1947 我们更新了 rest API 接口：https://docs.espressif.com/projects/esp-thread-br/en/latest/esp32/codelab/web-gui.html#web-gui-rest-apis，保持和 ot-br-posix 兼容。

**Comment by HeFeng1947** [comment]
> @HeFeng1947 我们更新了 rest API 接口：[https://docs.espressif.com/projects/esp-thread-br/en/latest/esp32/codelab/web-gui.html#web-gui-rest-apis，保持和](https://docs.espressif.com/projects/esp-thread-br/en/latest/esp32/codelab/web-gui.html#web-gui-rest-apis%EF%BC%8C%E4%BF%9D%E6%8C%81%E5%92%8C) ot-br-posix 兼容。

非常感谢，这个就是我们想要的，节省了我们自己开发的时间。
