### ISSUE TITLE
Masterkey Option Is Missing from Thread CLI (TZ-1013)

### ISSUE THREAD

**Issue by digidhamu** [espressif/esp-thread-br#82]
Could you please help me to understand as I could not see `masterkey` option in help command and I could not set.

I could see `networkkey`, `extpanid`, etc.,

Means, can I use `networkkey` as `masterkey` in the ESP Thread Board Router implementation?

**Comment by zwx1995esp** [comment]
The command `masterkey` has been changed to `networkkey` by openthread upstream. If you want to set the networkkey for the thread network, please use the command `networkkey`.

**Comment by digidhamu** [comment]
Great @zwx1995esp. Thanks for your advice.
