### ISSUE TITLE
When disabled AUTO_UPDATE_RCP in menuconfig, cannot build this project (TZ-1101)

### ISSUE THREAD

**Issue by zhengruiw02** [espressif/esp-thread-br#91]
When disabled option CONFIG_AUTO_UPDATE_RCP in menuconfig, then cannot compile project.

Double checked that missing macro checking for above option in file 'esp_ot_config.h' for below define.
`#define ESP_OPENTHREAD_RCP_UPDATE_CONFIG()  `
And also missing macro checking in function call 'launch_openthread_border_router' for disabled this feature checking.

> (base) henry@henry-Home:~/workspace/esp/esp-thread-br/examples/basic_thread_border_router$ idf.py build
> WARNING: Python interpreter "/home/henry/esp/esp-matter/connectedhomeip/connectedhomeip/.environment/pigweed-venv/bin/python" used to start idf.py is not from installed venv "/home/henry/esp/.espressif/python_env/idf5.2_py3.10_env"
> Executing action: all (aliases: build)
> Running ninja in directory /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build
> Executing "ninja all"...
> [0/1] Re-running CMake...
> -- ccache will be used for faster recompilation
> -- Building ESP-IDF components for target esp32c3
> Processing 6 dependencies:
> [6/6] idf (5.2.1)
> -- Project sdkconfig file /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/sdkconfig
> Loading defaults file /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/sdkconfig.defaults...
> -- App "esp_ot_br" version: v1.0-75-g6011f07
> -- Adding linker script /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build/esp-idf/esp_system/ld/memory.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_system/ld/esp32c3/sections.ld.in
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.api.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.libgcc.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.newlib.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.version.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.eco3.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/soc/esp32c3/ld/esp32c3.peripherals.ld
> -- Components: app_trace app_update bootloader bootloader_support bt cmock console cxx driver efuse esp-tls esp_adc esp_app_format esp_bootloader_format esp_br_http_ota esp_coex esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_lcd esp_local_ctrl esp_mm esp_netif esp_netif_stack esp_ot_br_server esp_partition esp_phy esp_pm esp_psram esp_ringbuf esp_rom esp_system esp_timer esp_wifi espcoredump espressif__esp-serial-flasher espressif__esp_ot_cli_extension espressif__esp_rcp_update espressif__iperf espressif__mdns esptool_py fatfs freertos hal heap http_parser idf_test ieee802154 json log lwip main mbedtls mqtt newlib nvs_flash nvs_sec_provider openthread partition_table protobuf-c protocol_examples_common protocomm pthread riscv sdmmc soc spi_flash spiffs tcp_transport thread_border_router ulp unity usb vfs wear_levelling wifi_provisioning wpa_supplicant
> -- Component paths: /home/henry/esp/v5.2.1/esp-idf/components/app_trace /home/henry/esp/v5.2.1/esp-idf/components/app_update /home/henry/esp/v5.2.1/esp-idf/components/bootloader /home/henry/esp/v5.2.1/esp-idf/components/bootloader_support /home/henry/esp/v5.2.1/esp-idf/components/bt /home/henry/esp/v5.2.1/esp-idf/components/cmock /home/henry/esp/v5.2.1/esp-idf/components/console /home/henry/esp/v5.2.1/esp-idf/components/cxx /home/henry/esp/v5.2.1/esp-idf/components/driver /home/henry/esp/v5.2.1/esp-idf/components/efuse /home/henry/esp/v5.2.1/esp-idf/components/esp-tls /home/henry/esp/v5.2.1/esp-idf/components/esp_adc /home/henry/esp/v5.2.1/esp-idf/components/esp_app_format /home/henry/esp/v5.2.1/esp-idf/components/esp_bootloader_format /home/henry/workspace/esp/esp-thread-br/components/esp_br_http_ota /home/henry/esp/v5.2.1/esp-idf/components/esp_coex /home/henry/esp/v5.2.1/esp-idf/components/esp_common /home/henry/esp/v5.2.1/esp-idf/components/esp_eth /home/henry/esp/v5.2.1/esp-idf/components/esp_event /home/henry/esp/v5.2.1/esp-idf/components/esp_gdbstub /home/henry/esp/v5.2.1/esp-idf/components/esp_hid /home/henry/esp/v5.2.1/esp-idf/components/esp_http_client /home/henry/esp/v5.2.1/esp-idf/components/esp_http_server /home/henry/esp/v5.2.1/esp-idf/components/esp_https_ota /home/henry/esp/v5.2.1/esp-idf/components/esp_https_server /home/henry/esp/v5.2.1/esp-idf/components/esp_hw_support /home/henry/esp/v5.2.1/esp-idf/components/esp_lcd /home/henry/esp/v5.2.1/esp-idf/components/esp_local_ctrl /home/henry/esp/v5.2.1/esp-idf/components/esp_mm /home/henry/esp/v5.2.1/esp-idf/components/esp_netif /home/henry/esp/v5.2.1/esp-idf/components/esp_netif_stack /home/henry/workspace/esp/esp-thread-br/components/esp_ot_br_server /home/henry/esp/v5.2.1/esp-idf/components/esp_partition /home/henry/esp/v5.2.1/esp-idf/components/esp_phy /home/henry/esp/v5.2.1/esp-idf/components/esp_pm /home/henry/esp/v5.2.1/esp-idf/components/esp_psram /home/henry/esp/v5.2.1/esp-idf/components/esp_ringbuf /home/henry/esp/v5.2.1/esp-idf/components/esp_rom /home/henry/esp/v5.2.1/esp-idf/components/esp_system /home/henry/esp/v5.2.1/esp-idf/components/esp_timer /home/henry/esp/v5.2.1/esp-idf/components/esp_wifi /home/henry/esp/v5.2.1/esp-idf/components/espcoredump /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__esp-serial-flasher /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__esp_ot_cli_extension /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__esp_rcp_update /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__iperf /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__mdns /home/henry/esp/v5.2.1/esp-idf/components/esptool_py /home/henry/esp/v5.2.1/esp-idf/components/fatfs /home/henry/esp/v5.2.1/esp-idf/components/freertos /home/henry/esp/v5.2.1/esp-idf/components/hal /home/henry/esp/v5.2.1/esp-idf/components/heap /home/henry/esp/v5.2.1/esp-idf/components/http_parser /home/henry/esp/v5.2.1/esp-idf/components/idf_test /home/henry/esp/v5.2.1/esp-idf/components/ieee802154 /home/henry/esp/v5.2.1/esp-idf/components/json /home/henry/esp/v5.2.1/esp-idf/components/log /home/henry/esp/v5.2.1/esp-idf/components/lwip /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main /home/henry/esp/v5.2.1/esp-idf/components/mbedtls /home/henry/esp/v5.2.1/esp-idf/components/mqtt /home/henry/esp/v5.2.1/esp-idf/components/newlib /home/henry/esp/v5.2.1/esp-idf/components/nvs_flash /home/henry/esp/v5.2.1/esp-idf/components/nvs_sec_provider /home/henry/esp/v5.2.1/esp-idf/components/openthread /home/henry/esp/v5.2.1/esp-idf/components/partition_table /home/henry/esp/v5.2.1/esp-idf/components/protobuf-c /home/henry/esp/v5.2.1/esp-idf/examples/common_components/protocol_examples_common /home/henry/esp/v5.2.1/esp-idf/components/protocomm /home/henry/esp/v5.2.1/esp-idf/components/pthread /home/henry/esp/v5.2.1/esp-idf/components/riscv /home/henry/esp/v5.2.1/esp-idf/components/sdmmc /home/henry/esp/v5.2.1/esp-idf/components/soc /home/henry/esp/v5.2.1/esp-idf/components/spi_flash /home/henry/esp/v5.2.1/esp-idf/components/spiffs /home/henry/esp/v5.2.1/esp-idf/components/tcp_transport /home/henry/workspace/esp/esp-thread-br/examples/common/thread_border_router /home/henry/esp/v5.2.1/esp-idf/components/ulp /home/henry/esp/v5.2.1/esp-idf/components/unity /home/henry/esp/v5.2.1/esp-idf/components/usb /home/henry/esp/v5.2.1/esp-idf/components/vfs /home/henry/esp/v5.2.1/esp-idf/components/wear_levelling /home/henry/esp/v5.2.1/esp-idf/components/wifi_provisioning /home/henry/esp/v5.2.1/esp-idf/components/wpa_supplicant
> -- Configuring done (9.8s)
> -- Generating done (0.2s)
> -- Build files have been written to: /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build
> [0/1] Re-running CMake...
> -- Building ESP-IDF components for target esp32c3
> -- Project sdkconfig file /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/sdkconfig
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/soc/esp32c3/ld/esp32c3.peripherals.ld
> -- Bootloader project name: "bootloader" version: 1
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.api.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.libgcc.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3/ld/esp32c3.rom.newlib.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/bootloader/subproject/main/ld/esp32c3/bootloader.ld
> -- Adding linker script /home/henry/esp/v5.2.1/esp-idf/components/bootloader/subproject/main/ld/esp32c3/bootloader.rom.ld
> -- Components: bootloader bootloader_support efuse esp_app_format esp_bootloader_format esp_common esp_hw_support esp_rom esp_system esptool_py freertos hal log main micro-ecc newlib partition_table riscv soc spi_flash
> -- Component paths: /home/henry/esp/v5.2.1/esp-idf/components/bootloader /home/henry/esp/v5.2.1/esp-idf/components/bootloader_support /home/henry/esp/v5.2.1/esp-idf/components/efuse /home/henry/esp/v5.2.1/esp-idf/components/esp_app_format /home/henry/esp/v5.2.1/esp-idf/components/esp_bootloader_format /home/henry/esp/v5.2.1/esp-idf/components/esp_common /home/henry/esp/v5.2.1/esp-idf/components/esp_hw_support /home/henry/esp/v5.2.1/esp-idf/components/esp_rom /home/henry/esp/v5.2.1/esp-idf/components/esp_system /home/henry/esp/v5.2.1/esp-idf/components/esptool_py /home/henry/esp/v5.2.1/esp-idf/components/freertos /home/henry/esp/v5.2.1/esp-idf/components/hal /home/henry/esp/v5.2.1/esp-idf/components/log /home/henry/esp/v5.2.1/esp-idf/components/bootloader/subproject/main /home/henry/esp/v5.2.1/esp-idf/components/bootloader/subproject/components/micro-ecc /home/henry/esp/v5.2.1/esp-idf/components/newlib /home/henry/esp/v5.2.1/esp-idf/components/partition_table /home/henry/esp/v5.2.1/esp-idf/components/riscv /home/henry/esp/v5.2.1/esp-idf/components/soc /home/henry/esp/v5.2.1/esp-idf/components/spi_flash
> -- Configuring done (1.3s)
> -- Generating done (0.0s)
> -- Build files have been written to: /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build/bootloader
> [96/97] Generating binary image from built executable
> esptool.py v4.6.2
> Creating esp32c3 image...
> Merged 2 ELF sections
> Successfully created esp32c3 image.
> Generated /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build/bootloader/bootloader.bin
> [97/97] cd /home/henry/workspace/esp/esp-thread-br/examples/...s/basic_thread_border_router/build/bootloader/bootloader.bin
> Bootloader binary size 0x50c0 bytes. 0x2f40 bytes (37%) free.
> [1202/1208] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/esp_ot_br.c.obj
> FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/esp_ot_br.c.obj 
> ccache /home/henry/esp/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20230928/riscv32-esp-elf/bin/riscv32-esp-elf-gcc -DESP_PLATFORM -DIDF_VER=\"v5.2.1-dirty\" -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DMD5_ENABLED=1 -DOPENTHREAD_CONFIG_FILE=\"openthread-core-esp32x-ftd-config.h\" -DOPENTHREAD_FTD=1 -DSERIAL_FLASHER_BOOT_HOLD_TIME_MS=50 -DSERIAL_FLASHER_RESET_HOLD_TIME_MS=100 -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DSOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ -DUNITY_INCLUDE_CONFIG_H -D_GLIBCXX_HAVE_POSIX_SEMAPHORE -D_GLIBCXX_USE_POSIX_SEMAPHORE -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build/config -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main -I/home/henry/esp/v5.2.1/esp-idf/components/newlib/platform_include -I/home/henry/esp/v5.2.1/esp-idf/components/freertos/config/include -I/home/henry/esp/v5.2.1/esp-idf/components/freertos/config/include/freertos -I/home/henry/esp/v5.2.1/esp-idf/components/freertos/config/riscv/include -I/home/henry/esp/v5.2.1/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/henry/esp/v5.2.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include -I/home/henry/esp/v5.2.1/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/include/freertos -I/home/henry/esp/v5.2.1/esp-idf/components/freertos/esp_additions/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_hw_support/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_hw_support/include/soc -I/home/henry/esp/v5.2.1/esp-idf/components/esp_hw_support/include/soc/esp32c3 -I/home/henry/esp/v5.2.1/esp-idf/components/heap/include -I/home/henry/esp/v5.2.1/esp-idf/components/log/include -I/home/henry/esp/v5.2.1/esp-idf/components/soc/include -I/home/henry/esp/v5.2.1/esp-idf/components/soc/esp32c3 -I/home/henry/esp/v5.2.1/esp-idf/components/soc/esp32c3/include -I/home/henry/esp/v5.2.1/esp-idf/components/hal/platform_port/include -I/home/henry/esp/v5.2.1/esp-idf/components/hal/esp32c3/include -I/home/henry/esp/v5.2.1/esp-idf/components/hal/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_rom/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_rom/include/esp32c3 -I/home/henry/esp/v5.2.1/esp-idf/components/esp_rom/esp32c3 -I/home/henry/esp/v5.2.1/esp-idf/components/esp_common/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_system/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_system/port/soc -I/home/henry/esp/v5.2.1/esp-idf/components/esp_system/port/include/riscv -I/home/henry/esp/v5.2.1/esp-idf/components/esp_system/port/include/private -I/home/henry/esp/v5.2.1/esp-idf/components/riscv/include -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/include -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/include/apps -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/include/apps/sntp -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/lwip/src/include -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/port/include -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/port/freertos/include -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/port/esp32xx/include -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/port/esp32xx/include/arch -I/home/henry/esp/v5.2.1/esp-idf/components/lwip/port/esp32xx/include/sys -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__esp_ot_cli_extension/include -I/home/henry/esp/v5.2.1/esp-idf/examples/common_components/protocol_examples_common/include -I/home/henry/workspace/esp/esp-thread-br/components/esp_br_http_ota/include -I/home/henry/esp/v5.2.1/esp-idf/components/app_update/include -I/home/henry/esp/v5.2.1/esp-idf/components/bootloader_support/include -I/home/henry/esp/v5.2.1/esp-idf/components/bootloader_support/bootloader_flash/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_app_format/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_bootloader_format/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_partition/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_http_client/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_event/include -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__esp_rcp_update/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/deprecated -I/home/henry/esp/v5.2.1/esp-idf/components/driver/analog_comparator/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/dac/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/gpio/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/gptimer/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/i2c/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/i2s/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/ledc/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/mcpwm/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/parlio/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/pcnt/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/rmt/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/sdio_slave/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/sdmmc/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/sigma_delta/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/spi/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/temperature_sensor/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/touch_sensor/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/twai/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/uart/include -I/home/henry/esp/v5.2.1/esp-idf/components/driver/usb_serial_jtag/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_pm/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_ringbuf/include -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__esp-serial-flasher/include -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__esp-serial-flasher/port -I/home/henry/esp/v5.2.1/esp-idf/components/nvs_flash/include -I/home/henry/esp/v5.2.1/esp-idf/components/spi_flash/include -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__mdns/include -I/home/henry/esp/v5.2.1/esp-idf/components/console -I/home/henry/esp/v5.2.1/esp-idf/components/vfs/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_netif/include -I/home/henry/esp/v5.2.1/esp-idf/components/efuse/include -I/home/henry/esp/v5.2.1/esp-idf/components/efuse/esp32c3/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_mm/include -I/home/henry/esp/v5.2.1/esp-idf/components/mbedtls/port/include -I/home/henry/esp/v5.2.1/esp-idf/components/mbedtls/mbedtls/include -I/home/henry/esp/v5.2.1/esp-idf/components/mbedtls/mbedtls/library -I/home/henry/esp/v5.2.1/esp-idf/components/mbedtls/esp_crt_bundle/include -I/home/henry/esp/v5.2.1/esp-idf/components/mbedtls/mbedtls/3rdparty/everest/include -I/home/henry/esp/v5.2.1/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m -I/home/henry/esp/v5.2.1/esp-idf/components/mbedtls/mbedtls/3rdparty/p256-m/p256-m -I/home/henry/esp/v5.2.1/esp-idf/components/pthread/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_timer/include -I/home/henry/esp/v5.2.1/esp-idf/components/app_trace/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_phy/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_phy/esp32c3/include -I/home/henry/esp/v5.2.1/esp-idf/components/wpa_supplicant/include -I/home/henry/esp/v5.2.1/esp-idf/components/wpa_supplicant/port/include -I/home/henry/esp/v5.2.1/esp-idf/components/wpa_supplicant/esp_supplicant/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_coex/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_wifi/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_wifi/wifi_apps/include -I/home/henry/esp/v5.2.1/esp-idf/components/unity/include -I/home/henry/esp/v5.2.1/esp-idf/components/unity/unity/src -I/home/henry/esp/v5.2.1/esp-idf/components/cmock/CMock/src -I/home/henry/esp/v5.2.1/esp-idf/components/http_parser -I/home/henry/esp/v5.2.1/esp-idf/components/esp-tls -I/home/henry/esp/v5.2.1/esp-idf/components/esp-tls/esp-tls-crypto -I/home/henry/esp/v5.2.1/esp-idf/components/esp_adc/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_adc/interface -I/home/henry/esp/v5.2.1/esp-idf/components/esp_adc/esp32c3/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_adc/deprecated/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_eth/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_gdbstub/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_hid/include -I/home/henry/esp/v5.2.1/esp-idf/components/tcp_transport/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_http_server/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_https_ota/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_psram/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_lcd/include -I/home/henry/esp/v5.2.1/esp-idf/components/esp_lcd/interface -I/home/henry/esp/v5.2.1/esp-idf/components/protobuf-c/protobuf-c -I/home/henry/esp/v5.2.1/esp-idf/components/protocomm/include/common -I/home/henry/esp/v5.2.1/esp-idf/components/protocomm/include/security -I/home/henry/esp/v5.2.1/esp-idf/components/protocomm/include/transports -I/home/henry/esp/v5.2.1/esp-idf/components/protocomm/include/crypto/srp6a -I/home/henry/esp/v5.2.1/esp-idf/components/esp_local_ctrl/include -I/home/henry/esp/v5.2.1/esp-idf/components/espcoredump/include -I/home/henry/esp/v5.2.1/esp-idf/components/espcoredump/include/port/riscv -I/home/henry/esp/v5.2.1/esp-idf/components/wear_levelling/include -I/home/henry/esp/v5.2.1/esp-idf/components/sdmmc/include -I/home/henry/esp/v5.2.1/esp-idf/components/fatfs/diskio -I/home/henry/esp/v5.2.1/esp-idf/components/fatfs/src -I/home/henry/esp/v5.2.1/esp-idf/components/fatfs/vfs -I/home/henry/esp/v5.2.1/esp-idf/components/idf_test/include -I/home/henry/esp/v5.2.1/esp-idf/components/idf_test/include/esp32c3 -I/home/henry/esp/v5.2.1/esp-idf/components/ieee802154/include -I/home/henry/esp/v5.2.1/esp-idf/components/json/cJSON -I/home/henry/esp/v5.2.1/esp-idf/components/mqtt/esp-mqtt/include -I/home/henry/esp/v5.2.1/esp-idf/components/nvs_sec_provider/include -I/home/henry/esp/v5.2.1/esp-idf/components/openthread/include -I/home/henry/esp/v5.2.1/esp-idf/components/openthread/openthread/include -I/home/henry/esp/v5.2.1/esp-idf/components/spiffs/include -I/home/henry/esp/v5.2.1/esp-idf/components/wifi_provisioning/include -I/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/managed_components/espressif__iperf/include -I/home/henry/workspace/esp/esp-thread-br/examples/common/thread_border_router/include -I/home/henry/workspace/esp/esp-thread-br/components/esp_ot_br_server/include -march=rv32imc_zicsr_zifencei  -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -nostartfiles -Os -freorder-blocks -fmacro-prefix-map=/home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router=. -fmacro-prefix-map=/home/henry/esp/v5.2.1/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -Wno-old-style-declaration -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/esp_ot_br.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/esp_ot_br.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/esp_ot_br.c.obj -c /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main/esp_ot_br.c
> In file included from /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main/esp_ot_br.c:19:
> /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main/esp_ot_br.c: In function 'app_main':
> /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main/esp_ot_config.h:79:29: error: expected '}' before 'CONFIG_RCP_PARTITION_NAME'
>    79 |         .firmware_dir = "/" CONFIG_RCP_PARTITION_NAME "/ot_rcp", .target_chip = ESP32H2_CHIP,                        \
>       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
> /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main/esp_ot_br.c:83:49: note: in expansion of macro 'ESP_OPENTHREAD_RCP_UPDATE_CONFIG'
>    83 |     esp_rcp_update_config_t rcp_update_config = ESP_OPENTHREAD_RCP_UPDATE_CONFIG();
>       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main/esp_ot_config.h:75:5: note: to match this '{'
>    75 |     {                                                                                                                \
>       |     ^
> /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/main/esp_ot_br.c:83:49: note: in expansion of macro 'ESP_OPENTHREAD_RCP_UPDATE_CONFIG'
>    83 |     esp_rcp_update_config_t rcp_update_config = ESP_OPENTHREAD_RCP_UPDATE_CONFIG();
>       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ninja: build stopped: subcommand failed.
> ninja failed with exit code 1, output of the command is in the /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build/log/idf_py_stderr_output_56885 and /home/henry/workspace/esp/esp-thread-br/examples/basic_thread_border_router/build/log/idf_py_stdout_output_56885

**Comment by chshu** [comment]
It's fixed by https://github.com/espressif/esp-thread-br/commit/93716d90858e466cb48b164d064b965f3a294127.
